### ISSUE TITLE
Screenpack - Fade out animation doesn't play

### ISSUE THREAD

**Issue by shinlucho** [K4thos/Ikemen-GO-Plus#10]
In any screenpack, on `[Select Info]` and `[Title Info]` sections, setting `fadeout.time` to a value greater than 0 (i.e 1000), fade out animation doesn't show and change to the next screen immediately.

`fadein.time` works fine, but there is a problem with `fadeout.time`

**Comment by K4thos** [comment]
fixed locally with new fadeScreen function added to source code, thanks for reporting
