### ISSUE TITLE
Linux - Error compiling syscall

### ISSUE THREAD

**Issue by shinlucho** [K4thos/Ikemen-GO-Plus#17]
I'm using a laptop with Lubuntu 17.10. When I try to compile Ikemen with `build.sh` after getting the dependencies with `get.sh`, Go throws an error on building:

```
src/main.go:46: undefined: syscall.NewLazyDLL
src/main.go:48: too many arguments in call to syscall.Syscall
        have (<T>, number, number, number, number)
        want (uintptr, uintptr, uintptr, uintptr)
src/main.go:49: undefined: syscall.GetStdHandle
src/main.go:49: undefined: syscall.STD_OUTPUT_HANDLE
src/main.go:50: undefined: syscall.GetStdHandle
src/main.go:50: undefined: syscall.STD_INPUT_HANDLE
```

Maybe it happens because there isn't a `kernel32.dll` on Linux, which is used to execute Ikemen from a console/terminal.

One way to solve this is having 2 main.go files:
* main_windows.go
* main_linux.go

I haven't tried it yet, but later I'll add a comment with the result.

**Comment by shinlucho** [comment]
I've managed to compile ikemen on linux removing this code in main:

```Go
modkernel32 := syscall.NewLazyDLL("kernel32.dll")
procAllocConsole := modkernel32.NewProc("AllocConsole")
syscall.Syscall(procAllocConsole.Addr(), 0, 0, 0, 0)
hout, err1 := syscall.GetStdHandle(syscall.STD_OUTPUT_HANDLE)
hin, err2 := syscall.GetStdHandle(syscall.STD_INPUT_HANDLE)
if err1 != nil || err2 != nil { // nowhere to print the message
  os.Exit(2)
}
os.Stdout = os.NewFile(uintptr(hout), "/dev/stdout")
os.Stdin = os.NewFile(uintptr(hin), "/dev/stdin")
```
No idea what is its purpose, but still keeps working on linux without it :P. 
@K4thos Do you know what this does?

**Comment by TurBoss** [comment]
got a fix but needs to be tested on windows

once I test it I'll make a PR

**Comment by Pollito001** [comment]
How i Fix this issue?
I already rename folder and nothing happens
![ikemen](https://user-images.githubusercontent.com/4990486/60776237-ab6ea700-a0f8-11e9-932b-9ac35aae9305.png)

**Comment by LucasFebatis** [comment]
> How i Fix this issue?
> I already rename folder and nothing happens
> ![ikemen](https://user-images.githubusercontent.com/4990486/60776237-ab6ea700-a0f8-11e9-932b-9ac35aae9305.png)

This is because he is looking for the training.def file and not Training.def as it appears in the message.

I found this out by looking at the main.lua file

**Comment by ca3games** [comment]
Can confirm this bug still exist.

**Comment by Askmewho** [comment]
Ok, i am facing the same issue, but original mugen 1.0 haven training.def, Where I suppose to get that one?

**Comment by K4thos** [comment]
https://github.com/Windblade-GR01/Ikemen_GO/blob/master/build/Build_linux.md
