### ISSUE TITLE
Show whole team portraits on Victory Screen

### ISSUE THREAD

**Issue by shinlucho** [K4thos/Ikemen-GO-Plus#2]
Now, victory screen only shows team leader's portrait. It would be nice to have an option to show everyone's portrait and adjust their position on system.def

**Comment by K4thos** [comment]
good idea. For select screen and versus screen I've already implemented it by adding following parameters to [VS Screen] section of screenpack def:

> p1.num = x (limits how many P1 portraits should be displayed, default value = 1)
> p1.spacing = x, y (x, y spacing between portraits)
> p2.num = x
> p2.spacing = x, y

Should the victory screen follow the same implementation or you think each one of the team members portrait position should be adjustable? To replicate some KOF games the second approach may be more preferable.

**Comment by K4thos** [comment]
feature implemented locally
