### ISSUE TITLE
Victory quotes on Victory screen

### ISSUE THREAD

**Issue by shinlucho** [K4thos/Ikemen-GO-Plus#3]
Now, victory screen always shows "Winner!" quote and it doesn't read character's quotes. The idea is to find a way to implement the same functionality that mugen 1.0 has.

**Comment by K4thos** [comment]
I'm working on it right now. Should be ready in a day or two and will work exactly the same as in mugen (all victory quote CNS coding present in characters is taken into account).

**Comment by K4thos** [comment]
Victory quotes functionality has been implemented in last commit.
