### ISSUE TITLE
[Enhancement] Local High Scores

### ISSUE THREAD

**Issue by Emerik1995** [K4thos/Ikemen-GO-Plus#32]
I would like to add a local high scores like they did in the original arcade game.

It could be like the 80s and early-90s high scores for the top 5 or you can set your numbers of high scores like top 10, 15 or 20.

**Comment by MrEmerik2000** [comment]
Sometimes, the local high scores will scroll downward from top 10 or worse until they stop to top 1.

**Comment by MrEmerik2000** [comment]
Otherwise, in Primal Rage, the high scores is different: If you are at number 1, you can enter your name entirely (e.g. Emerik Steben-Taillon). Or if you are at number 2 or worse, you can enter your initial name. (e.g. EST)

**Comment by K4thos** [comment]
already requested: #6
