### ISSUE TITLE
[Enhancement] A new challenger approaching!

### ISSUE THREAD

**Issue by Emerik1995** [K4thos/Ikemen-GO-Plus#34]
I would like to see a text pop up that says: A new challenger approaching! from SF2 or later, or the Warning: Challenger Approaching storyboard one from Super Smash Bros. when a new player joins the fight.

It will make sense if the entire fight just stops and bring back to the select screen when a new challenger choose a new character while the player who's playing the game (gets stuck at his chosen character) try to defend the title.

**Comment by K4thos** [comment]
implemented in this commit: https://github.com/K4thos/Ikemen-GO-Plus/commit/68f80903ec3f0b3e2364c551904f3e83e67fb06d
