### ISSUE TITLE
High level architecture overview

### ISSUE THREAD

**Issue by MicahMartin** [K4thos/Ikemen-GO-Plus#36]
Any chance you could write something up on the high level architecture? I'm not too familiar with go, but it looks like you're using go as an engine with the lua embedding as a way to have modular games. I'm a bit lost as to what happens from here, like where are the character statedefs being read/changed? if this is too vague let me know and I'll come up with some specific questions

**Comment by Windblade-GR01** [comment]
Hello there.
Ikemen GO is a engine designed to be open source version of Elecbyte's Mugen.
The engine uses lua to parse the Mugen's "screenpacks" (These provide the game menus) the character parser is written in GO.

Mugen uses a proprietary format for sprites and audio.
The animations are saved to "gi.anim" (A table that contains the values) by the function "ReadAnimationTable" inside a "char" object.
These are played later according to the character code.
The character use something called CNS, that is technically the code of the characters.
These code is handled by ``compiler.go`` and ``bytecode.go``

``compiler.go`` read and interprets the CNS file and stores it for later access.
``bytecode.go`` takes what ``compiler.go`` did and executes the code on the characters when needed.

Sorry for the not in deep explanation I'm really bad explaining things.


If you want a modular games using only lua to parse the character actions is a better idea.
Also you need to create a animation system that supports multiple hitboxes.

**Comment by MicahMartin** [comment]
@Windblade-GR01 Thanks man, youre clutch. I'm coming up with a DSL for the character VM now

( I would just embed lua / python, but when am I ever gonna get the excuse to create my own light scripting language again? 😎 )
