### ISSUE TITLE
[Enhancement] Character Select Loop Toggle

### ISSUE THREAD

**Issue by Emerik1995** [K4thos/Ikemen-GO-Plus#37]
The original IKEMEN game engine had the character select loops. (e.g. kfm, randomselect, kfm, randomselect, ...) I wish If we can toggle the character select loop on or off to be more fitting with the original MUGEN game engine. (e.g. kfm, randomselect)

**Comment by K4thos** [comment]
current script files already support optional scrolling select screens via screenpack DEF parameter:
'rows.scrolling'
