### ISSUE TITLE
[Help] Update chance to Ikemen

### ISSUE THREAD

**Issue by CTFik** [K4thos/Ikemen-GO-Plus#39]
I recently discovered this Ikemen project and I think it's amazing, but I have a question about how to update the changes.

I have an ikemen that still has the problem of fade out, a problem that has been solved for some time, but I do not know how to update the ikemen with the new fixes that have been made to the code.

I know this is a novice question ... but I must know that so simple.

**Comment by Windblade-GR01** [comment]
Hey so I'll will inform you of the state of Ikemen.
There are 2 version Ikemen and Ikemen GO.

Ikemen is no longer under development.
You can find info about it here:
http://mugenguild.com/forum/topics/ikemen-plus-181972.0.html

Ikemen Go (This repo) is a rewrite of the engine that is under development.
http://mugenguild.com/forum/topics/ikemen-go-plus-184152.0.html

Sadly K4thos abandoned development but there is other people that continue working on it on different repos.

**Comment by ikingofrandom** [comment]
Is there any chance to compile it for android?

**Comment by Windblade-GR01** [comment]
Right now there is someone called Dan trying to do that.
I'll contact him.

**Comment by CTFik** [comment]
So guys, to create the last IKEMEN GO PLUS modified with the latest fixes such as fade out correction and so on ...
Do I have to do the building process?
Previously I tried but the result was an IKEMEN with the errors of transparency and fade out, so, how do I get the IKEMEN already with the corrected errors?

**Comment by Windblade-GR01** [comment]
We have a builds at AppVeyor
https://ci.appveyor.com/project/Windblade-GR01/ikemen-go/build/artifacts
These are automated so it's always updated.

You have to download the zip for your os and the mugen files:
https://drive.google.com/file/d/1YCp5LYq-v1LSCFiq7a4RxLmJHdwZ4b0s/view

Extract both in the same folder and you are ready to go!

**Comment by CTFik** [comment]
Yes, that's exactly what I'm looking for, thanks buddy, I appreciate it.
I think we can close this.
