### ISSUE TITLE
Can you launch the Appveyor for your IKEMEN GO?

### ISSUE THREAD

**Issue by cyliamargatroid** [K4thos/Ikemen-GO-Plus#43]
I know Gacel had his IKEMEN GO in Appveyor.
Are you able to use Appveyor?

**Comment by K4thos** [comment]
what's currently here is not yet in a state worth of distributing. Once scripts are up to date feature and polish wise with what's on other forks than (I think/hope) these commits will be merged to @Windblade-GR01 repo, so dedicated Appveyor for this fork may not be needed. Notice that I'm currently not even linking to this repo on MFG topic.

**Comment by K4thos** [comment]
courtesy of Gacel: https://ci.appveyor.com/project/Windblade-GR01/ikemen-go-plus
