### ISSUE TITLE
Enhancement: Can you add Statedef -12 and Statedef -13 for Project-Focused stuff I'm doing?

### ISSUE THREAD

**Issue by cyliamargatroid** [K4thos/Ikemen-GO-Plus#45]
I was working on the MUGEN Project, I can easly add -12 and -13, Keeping -2, -3, -20 and -30
You think this an easy enhancement?

**Comment by K4thos** [comment]
The only reason there are -10, -20, -30 variants is because we needed states that work globally for stuff like implementing Tag mode without patching characters etc. I can't see any benefit in duplicating this functionality - you certainly didn't explain why you need it in the first place.

**Comment by cyliamargatroid** [comment]
I know, I can do It Manually still.
