### ISSUE TITLE
Stuck at step 5 on part 1 of the BUILD_win page.

### ISSUE THREAD

**Issue by Emerik1995** [K4thos/Ikemen-GO-Plus#46]
I finished step 1 2 3 and 4 on the first part of the BUILD_win page.

But now I'm stuck on step 5 by this following:
_From that file, inside include folder, extract AL folder to the <insert MSYS2 install folder here>/mingw64/include directory._

How do I suppose to **extract the AL folder** in the include directory? Do I have to create an AL folder? Do I have to search from the .zip file?

**Comment by K4thos** [comment]
6 files extracted to mingw64\include\AL directory
